apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-local-dns
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: kube-system
  project: cx-devops
  source:
    path: "{{ .Values.spec.source.path }}/charts/node-local-dns"
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ShowDiff=true
