apiVersion: v2
name: node-local-dns
description: A Helm chart for Kubernetes
type: application
version: 1.24.0
appVersion: "1.24.0"

icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.svg

keywords:
- node
- dns
- cache
- kubernetes

sources:
- https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns/nodelocaldns

