{{- range .Values.nodeClasses }}
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: {{ .name }}
spec:
  # Required, resolves a default ami and userdata
  amiFamily: {{ .spec.amiFamily | default "AL2" }}

  {{- if .spec.blockDeviceMappings }}
  blockDeviceMappings: 
    {{- range .spec.blockDeviceMappings }}
    - deviceName: {{ .deviceName | default "/dev/xvda" }}
      ebs:
        volumeSize: {{ .volumeSize | default "30Gi"}}
        volumeType: {{ .volumeType | default "gp3" }}
        deleteOnTermination: {{ .deleteOnTermination | default "true" }}
        throughput: {{ .throughput | default "128" }}
    {{- end }}
  {{- end }}

  # Required, discovers subnets to attach to instances
  # Each term in the array of subnetSelectorTerms is ORed together
  # Within a single term, all conditions are ANDed
  subnetSelectorTerms:
    {{- $subnetIds := .spec.subnetIds | default $.Values.global.subnetIds }}
    {{- range $subnetIds }}
    - id: {{ . }}
    {{- end }}

  # Required, discovers security groups to attach to instances
  # Each term in the array of securityGroupSelectorTerms is ORed together
  # Within a single term, all conditions are ANDed
  securityGroupSelectorTerms:
    # Select on any security group that has both the "karpenter.sh/discovery: ${CLUSTER_NAME}" tag
    # AND the "environment: test" tag OR any security group with the "my-security-group" name
    # OR any security group with ID "sg-063d7acfb4b06c82c"
    {{- $securityGroupIds := .spec.securityGroupIds | default $.Values.global.securityGroupIds }}
    {{- range $securityGroupIds }}
    - id: {{ . }}
    {{- end }}

  # Optional, IAM role to use for the node identity.
  # The "role" field is immutable after EC2NodeClass creation. This may change in the
  # future, but this restriction is currently in place today to ensure that Karpenter
  # avoids leaking managed instance profiles in your account.
  # Must specify one of "role" or "instanceProfile" for Karpenter to launch nodes
  # role: "arn:aws:iam::273032478126:role/shop-eks-nonprod-eks-cluster-karpenter-node-role"

  # Optional, IAM instance profile to use for the node identity.
  # Must specify one of "role" or "instanceProfile" for Karpenter to launch nodes
  instanceProfile: {{ .spec.instanceProfile | default $.Values.global.instanceProfile }}

  # Optional, discovers amis to override the amiFamily's default amis
  # Each term in the array of amiSelectorTerms is ORed together
  # Within a single term, all conditions are ANDed
  amiSelectorTerms:
    # Select on any AMI that has both the "karpenter.sh/discovery: ${CLUSTER_NAME}" tag
    # AND the "environment: test" tag OR any AMI with the "my-ami" name
    # OR any AMI with ID "ami-123"
    {{- $amiIds := .spec.amiIds | default $.Values.global.amiIds }}
    {{- range $amiIds }}
    - id: {{ . }}
    {{- end }}

  # Optional, overrides autogenerated userdata with a merge semantic
  userData: |
    #!/bin/bash
    sudo yum install -y htop
    sudo yum install -y 'https://s3.{{ .region | default "us-east-1" }}.amazonaws.com/amazon-ssm-{{ .region | default "us-east-1" }}/latest/linux_amd64/amazon-ssm-agent.rpm'

    #update ulimits on node instances
    ulimit -Sn 65535
    ulimit -Hn 65535

    #Set ipv4 tcp timeouts for NLB compatibility
    sudo sysctl -w net.ipv4.tcp_keepalive_time=60
    sudo sysctl -w net.ipv4.tcp_keepalive_intvl=10
    sudo sysctl -w net.ipv4.tcp_keepalive_probes=6
    sudo sysctl -w vm.max_map_count=262144

    #Removes in-built Datadog agent
    sudo systemctl stop datadog-agent
    sudo yum remove -y datadog-agent

  # Optional, propagates tags to underlying EC2 resources
  tags:
    {{- range $key, $value := $.Values.global.tags }}
    "{{ $key }}": "{{ $value }}"
    {{- end }}
    "Name": "karpenter-{{ .name }}-node-pool-{{ $.Values.global.clusterName}}"
    "NodePool": "{{ .name }}"
    "Cluster": "{{ $.Values.global.clusterName }}"
    "ProvisionedBy": "karpenter" 

  # Optional, configures IMDS for the instance
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: optional
---
{{- end }}